name: Update quick-ecs Formula

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g., v1.0.20250111). If empty, will use latest"
        required: false
  repository_dispatch:
    types: [quick-ecs-release]
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: write

jobs:
  bump-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tap
        uses: actions/checkout@v4

      - name: Resolve tag
        id: resolve
        env:
          DISPATCH_TAG: ${{ github.event.client_payload.tag }}
          INPUT_TAG: ${{ github.event.inputs.tag }}
        run: |
          TAG="${INPUT_TAG:-${DISPATCH_TAG}}"
          if [ -z "$TAG" ]; then
            TAG=$(gh api repos/bevelwork/quick_ecs/releases/latest --jq .tag_name)
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download tarball and compute sha256
        id: tar
        run: |
          URL="https://github.com/bevelwork/quick_ecs/archive/refs/tags/${{ steps.resolve.outputs.tag }}.tar.gz"
          curl -sSL "$URL" -o source.tgz
          SHA=$(sha256sum source.tgz | awk '{print $1}')
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Update quick-ecs.rb
        run: |
          FILE=Formula/quick-ecs.rb
          # Ensure stable url/sha256 entries exist and are updated
          if grep -q '^\s*url\s*"https://github.com/bevelwork/quick_ecs' "$FILE"; then
            sed -i "s|^\s*url\s*\"https://github.com/bevelwork/quick_ecs.*|  url \"${{ steps.tar.outputs.url }}\"|" "$FILE"
          else
            awk -v u="  url \"${{ steps.tar.outputs.url }}\"" '1; NR==6{print u}' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
          fi
          if grep -q '^\s*sha256\s*"' "$FILE"; then
            sed -i "s|^\s*sha256\s*\".*\"|  sha256 \"${{ steps.tar.outputs.sha }}\"|" "$FILE"
          else
            awk -v s="  sha256 \"${{ steps.tar.outputs.sha }}\"" '1; /url \\"https:\\/\\/github.com\\/bevelwork\\/quick_ecs/{print s}' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
          fi

          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add "$FILE"
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "quick-ecs: bump to ${{ steps.resolve.outputs.tag }}"
          git push


